services:
  amcbackend:
    container_name: amcbackend
    image: janine65/amcbackend:latest
    platform: linux/amd64
    stdin_open: true
    build:
      context: ../amc-backend-new/
      dockerfile: ../amc-backend-new/Dockerfile
    tty: true # Keeps the container running for debugging
    env_file:
      - .env.prod
    environment:
      - COMPOSE_PROJECT_NAME
      - NODE_ENV=production
    ports:
      - 5455:5455
    hostname: amcbackend
    networks:
      - back-tier
      - front-tier

  amcinternal:
    container_name: amcinternal
    image: janine65/amcinternal:latest
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - amcbackend
    environment:
      - COMPOSE_PROJECT_NAME
      - NODE_ENV=production
    ports:
      - 4200:4200
    links:
      - amcbackend
    hostname: amcinternal
    networks:
      - front-tier

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}
