services:
  amcbackend:
    build:
      context: ../amc-backend/
      dockerfile: ../amc-backend/Dockerfile
    image: janine65/amcbackend:latest
    platform: linux/amd64
    ports:
      - "3001:3001"
    stdin_open: true
    container_name: amcbackend
    tty: true # Keeps the container running for debugging
    volumes:
      - documents:/usr/src/app/dist/src/documents:rw
    env_file:
      - .env.prod
    networks:
      - back-tier
      - front-tier

  amcinternal:
    container_name: amcinternal
    image: janine65/amcinternal:latest
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - amcbackend
    environment:
      - COMPOSE_PROJECT_NAME
      - NODE_ENV=production
    ports:
      - 4200:4200
    links:
      - amcbackend
    hostname: amcinternal
    networks:
      - front-tier

volumes:
  backup:
    driver: local
    driver_opts:
      type: "nfs"
      o: "bind"
      device: "/volume1/dev/backups/postgres"
  documents:
    driver: local
    driver_opts:
      type: "nfs"
      o: "bind"
      device: "/volume1/server/amcinterna/documents"

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}
