services:
  amcbackend:
    build:
      context: ../amc-backend-py/
      dockerfile: ../amc-backend-py/Dockerfile
      tags:
        - "janine65/amcbackend:${BACKEND_VERSION:-latest}"
    image: janine65/amcbackend
    env_file:
      - ../amc-backend-py/.env-prod
    platform: linux/amd64
    ports:
      - "3001:3001"
    stdin_open: true
    container_name: amcbackend
    tty: true # Keeps the container running for debugging
    volumes:
      - documents:/usr/src/app/dist/src/documents:rw
    networks:
      - back-tier
      - front-tier

  amcinternal:
    container_name: amcinternal
    image: janine65/amcinternal
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile
      tags:
        - "janine65/amcinternal:${APP_VERSION:-latest}"
    depends_on:
      - amcbackend
    environment:
      - COMPOSE_PROJECT_NAME
      - NODE_ENV=production
    ports:
      - 4200:4200
    links:
      - amcbackend
    hostname: amcinternal
    networks:
      - front-tier

volumes:
  documents:
    driver: local
    driver_opts:
      type: "nfs"
      o: "bind"
      device: "/volume1/server/amcinterna/documents"

networks:
  # The presence of these objects is sufficient to define them
  front-tier: {}
  back-tier: {}
